### PR TITLE
Feature 17: Fix for issue# 17

### LINKED ISSUE #17: Role for Employee 3 should be updated to an Architect.
Role for Employee 3 should be updated to an Architect.
Changes can be made to the employee array list in the graph org tree component ts.

### PR DESCRIPTION
**Pull request by NaveenKCBits**
Fixed Issue #17  - Role updated as Architect for Employee 3.

### CODE REVIEW

**Review by MariamAkhtar — APPROVED** [review]
looks good

**Review by MariamAkhtar — COMMENTED** [review]
Resolved Conflicts

**Review by MariamAkhtar — CHANGES_REQUESTED** [review]
resolve conflicts

**Review by MariamAkhtar — APPROVED** [review]
tested and verified.

**Comment by msmehra** [comment]
Code was not merged properly, so reopening it.

**Review by MariamAkhtar — APPROVED** [review]
approved

**Pull request merged**
